  
Vagrant.configure("2") do |config|
	config.vm.define "vm3" do |vm3|
		config.vm.box = "ubuntu/trusty64"
		config.vm.network "private_network", ip: "192.168.10.3"
		config.vm.hostname = "chernenok_vm_3"
		config.vm.provider :virtualbox do |vb|
			vb.name = "chernenokVM3" 
			vb.gui = true
			vb.cpus = 1
			vb.memory = "512"
		end
	end
end
