Vagrant.configure("2") do |config|
	config.vm.define "vm1" do |vm1|
		config.vm.box = "ubuntu/trusty64"
		config.vm.network "private_network", ip: "192.168.10.1"
		config.vm.hostname = "chernenok_vm_1"
		config.vm.provider :virtualbox do |vb|
			vb.name = "chernenokVM1" 
			vb.gui = true
			vb.cpus = 1
			vb.memory = "512"
		end
	end
end
